Update zellij_run

diff --git a/zellij_run b/zellij_run
--- a/zellij_run
+++ b/zellij_run
@@ -24,32 +24,68 @@ export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6
 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4 --ansi --cycle'
 
-# clear the screen
-clear
+# zellij functions #
 
-echo -e "${GREEN}Welcome to zellij runner!${NC}\n\n"
+function attach_session {
+	local session_name
 
-options=('attach' 'create' 'list' 'delete')
-PS3="${PURPLE}Please enter your choice: ${BLUE}"
-echo -en "${BLUE}"
-select choice in "${options[@]}"; do
-	echo -e "${NC}"
+	session_name="$(zellij ls \
+		| fzf --header "Select session to attach" --prompt "Session: " \
+		| awk '{print $1}')"
 
-	case "$choice" in
-		'attach')
-			session_name="$(zellij ls \
-				| fzf --header "Select session to attach" --prompt "Session: " \
-				| awk '{print $1}')"
-			zellij a "$session_name"
-			exit 0 ;;
-		'create')
-			read -p "${BLUE}Session name ${RED}(Leave empty to abort)${BLUE}: ${YELLOW}" -r session_name
-			echo -en "${NC}"
-			[ -z "$session_name" ] && continue
-			zellij -s "$session_name"
-			exit 0 ;;
-		'delete') zellij ls | fzf -m --header "Select sessions to delete" \
-			| awk '{print $1}' | xargs -I {} zellij delete-session {} ; exit 0 ;;
-		'list') zellij ls | less -SR ;;
-	esac
-done
+	zellij a "$session_name"
+	exit 0
+}
+
+function create_session {
+	read -p "${BLUE}Session name ${RED}(Leave empty to abort)${BLUE}: ${YELLOW}" -r session_name
+	echo -en "${NC}"
+	[ -z "$session_name" ] && return 1
+	zellij -s "$session_name"
+	exit 0
+}
+
+function delete_session {
+	zellij ls | fzf -m --header "Select sessions to delete" \
+		| awk '{print $1}' | xargs -I {} zellij delete-session {}
+	exit 0
+}
+
+function list_sessions {
+	zellij ls | less -SR
+}
+
+function main_script {
+	clear
+	echo -e "${GREEN}Welcome to zellij runner!${NC}\n\n"
+
+	options=('attach' 'create' 'list' 'delete')
+	PS3="${PURPLE}Please enter your choice: ${BLUE}"
+	echo -en "${BLUE}"
+	select choice in "${options[@]}"; do
+		echo -e "${NC}"
+
+		case "$choice" in
+			'attach') attach_session;;
+			'create') create_session;;
+			'list') list_sessions;;
+			'delete') delete_session;;
+		esac
+	done
+}
+
+# Main Script #
+
+action="$1"
+if [ -z "$action" ]; then main_script && exit 0; fi
+
+case "$action" in
+	'attach'|'a') attach_session;;
+	'create'|'new') create_session;;
+	'list'|'ls') list_sessions;;
+	'delete'|'rm') delete_session;;
+	*)
+		echo -e "${RED}Invalid action: ${YELLOW}$action${NC}"
+		echo -e "${BLUE}Valid actions: ${GREEN}attach|a, create|new, list|ls, delete|rm${NC}"
+		exit 1;;
+esac
